name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - '16'
        platform:
          - ios
          - macos
          - examples

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run package tests
      run: make test-swift
    - name: Run build
      run: make build-${{ matrix.platform }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
