name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - '16'
        variant:
          - package
          - ios
          - macos
          - examples

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Run build
      run: make build-${{ matrix.variant }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  test:
    name: test
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - '16'
        variant:
          - package

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Get swift version
      run: swift --version
    - name: Run tests
      run: make test-${{ matrix.variant }}
