# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Xcode Select
      run: sudo xcode-select -s /Applications/Xcode_16.app
    - name: Get swift version
      run: swift --version
    - name: Install
      run: brew install swift-format
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Format
      run: make format
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Run swift-format
        branch: 'main'
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
